filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

#- decode_json_fields:
#    fields: ["message"]
#    target: "json"
#    overwrite_keys: true

# Custom field which represents the env we get logs from
fields:
    env: staging

#output.elasticsearch:
#  hosts: ["192.168.1.5:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
